#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import LaserScan

def scan_callback(msg):
    ranges = msg.ranges
    print(f'front: {ranges[0]:5.3f} \tleft: {ranges[90]:5.3f} \tright: {ranges[270]:5.3f}')


if __name__ == '__main__':
    rospy.init_node('print_front_distance')
    laser_sub = rospy.Subscriber('scan', LaserScan, scan_callback)
    rospy.spin()

